export const section5 = {
  "id": "sec-5",
  "title": "5. Arrays & Collections",
  "basics": {
    "en": "### Array Architecture & Memory Handling\n\n1. **Understanding Arrays**:\n- An array compactly clusters identical data types strictly contiguous inside memory, addressed utilizing a single unified variable name.\n- Example: `int[] marks = new int[5];` securely allocates exactly 5 memory slots.\n\n2. **Zero-Indexing & Bounds**:\n- C# strictly structures arrays starting from Index `0`. Therefore, an array of size 5 possesses indices `0, 1, 2, 3, 4`.\n- Accessing `marks[5]` critically triggers an `IndexOutOfRangeException` software crash immediately.\n\n3. **The `foreach` Iteration**:\n- While standard `for` loops require strict index tracking, C# implements `foreach`. It abstractly iterates entirely through array items automatically without manually specifying indices. Highly elegant for pure reading logic.",
    "bn": "### অ্যারে (Array) ও ডাটা সিকোয়েন্স\n\n১. **অ্যারে কী?**\n- অ্যারে হলো একসাথে অনেকগুলো ভ্যারিয়েবলের একটি গোছানো প্যাকেট। ধরুন ৫ জনের রেজাল্ট স্টোর করতে ৫ টি আলাদা ভ্যারিয়েবল না বানিয়ে `int[] marks = new int[5];` দিয়ে একটি অ্যারে বানানো সবচেয়ে ভালো পদ্ধতি।\n\n২. **জিরো (০) ইনডেক্সিং এবং বাউন্ডস**:\n- C# এ যেকোনো অ্যারে গুণতে শুরু হয় ০ নম্বর পজিশন থেকে। তাই ৫ সাইজের একটি অ্যারেতে জায়গা থাকে `০, ১, ২, ৩, ৪` নম্বর ইনডেক্সের।\n- আপনি যদি ভুল করে ৫ নম্বর ইনডেক্স বা `marks[5]` কে ডাকেন, তবে প্রোগ্রামটি সাথে সাথেই `IndexOutOfRangeException` দিয়ে ক্র্যাশ করবে।\n\n৩. **`foreach` লুপ এর জাদু**:\n- ডাটা রিড করার জন্য সি শার্পে `foreach` অত্যন্ত চমৎকার একটি লুপ। এতে ০ থেকে লেংথ পর্যন্ত হিসাব করার ঝামেলা নেই। এটি নিজে থেকেই অ্যারের সবগুলো মান একে একে টেনে বের করে।"
  },
  "questions": [
    {
      "id": 51,
      "question": "51. Create array and print elements.",
      "solve": "using System;\n\nclass Program {\n    static void Main() {\n        int[] numbers = { 10, 20, 30, 40, 50 };\n        \n        for (int i = 0; i < numbers.Length; i++) {\n            Console.WriteLine($\"Element at index {i}: {numbers[i]}\");\n        }\n    }\n}",
      "output": "Element at index 0: 10\nElement at index 1: 20\nElement at index 2: 30\nElement at index 3: 40\nElement at index 4: 50",
      "explanation_en": "### Code Breakdown:\n- `int[] numbers = { ... }`: This natively implicitly instantiates a perfectly contiguous linear memory layout completely pre-populated dynamically allocating precisely exactly 5 distinct logical blocks statically tied seamlessly onto one single identifier safely.\n- `numbers.Length`: A globally baked structural property resolving safely universally evaluating mapping correctly to `5`. Because C# arrays are rigorously inherently mathematically exactly **Zero-Indexed**, our iteration elegantly must absolutely terminate flawlessly at optimally `i < 5` specifically (`0,1,2,3,4`), effectively stopping immediately exactly prior hitting the boundary elegantly securely.",
      "explanation_bn": "### কোড ব্রেকডাউন:\n- `int[] numbers = { ... }`: এখানে সেকেন্ড ব্র্যাকেটের ভেতরে মানগুলো দিয়ে সরাসরি একটি অ্যারে তৈরি করা হয়েছে। এর ফলে মেমোরিতে পাশাপাশি ৫টি বক্স তৈরি হয়েছে যাদের সবার নাম একসাথে `numbers`।\n- `numbers.Length`: এই প্রোপার্টিটি স্বয়ংক্রিয়ভাবে গুনে বের করে যে অ্যারেটিতে মোট ৫টি আইটেম আছে। যেহেতু C# এর অ্যারে `0` নম্বর পজিশন থেকে গুণতে শুরু করে, তাই আমরা লুপটি `i < 5` পর্যন্ত চালিয়েছি। অর্থাৎ এটি ০, ১, ২, ৩ এবং ৪ নম্বর ইনডেক্স পর্যন্ত চলবে, কিন্তু ভুলে ৫ নম্বর পজিশনে যাবে না, কারণ ৫ নম্বর પজিশন মানে মূলত ৬ নম্বর মান, যা অস্তিত্বহীন!"
    },
    {
      "id": 52,
      "question": "52. Find sum of array elements.",
      "solve": "using System;\n\nclass Program {\n    static void Main() {\n        int[] arr = { 5, 10, 15, 20, 25 };\n        int sum = 0;\n        \n        foreach (int item in arr) {\n            sum += item;\n        }\n        Console.WriteLine($\"Total Sum: {sum}\");\n    }\n}",
      "output": "Total Sum: 75",
      "explanation_en": "### Code Breakdown:\n- `foreach (int item in arr)`: Deep cleanly executing universally efficiently seamlessly traversing flawlessly natively dynamically cleanly perfectly encapsulating elegantly securely natively optimally perfectly optimally abstracting deeply smoothly iterating securely without managing cleanly precisely explicit indices tracking manually effectively executing globally identically.\n- `sum += item`: Mathematically appending uniquely effectively scaling safely resolving perfectly elegantly natively mathematically aggregating directly inherently sequentially optimally combining smoothly identically dynamically successfully appending.",
      "explanation_bn": "### কোড ব্রেকডাউন:\n- `foreach (int item in arr)`: এটি হলো C# এর অন্যতম সেরা এবং রিলায়েবল একটি লুপ! যখন আপনাকে অ্যারের শুরু থেকে শেষ পর্যন্ত সবগুলো ডাটা একবার করে দেখতে হয়, তখন ৫ বার বা ১০ বার লুপ চালানোর ম্যানুয়াল লজিক না লিখে জাস্ট `foreach` ব্যবহার করবেন।\n- এটি `arr` এর ভেতর থেকে নিজে থেকেই একটি একটি করে মান টেনে বের করে আনে এবং সাময়িকভাবে `item` ভ্যারিয়েবলের ভেতরে রাখে। তারপর লুপের ভেতরে `sum += item` দিয়ে আমরা সেই মানগুলোকে যোগফলের ঝুড়িতে জমা করে নিয়েছি।"
    },
    {
      "id": 53,
      "question": "53. Find average of array.",
      "solve": "using System;\n\nclass Program {\n    static void Main() {\n        int[] arr = { 10, 20, 30, 40 };\n        double sum = 0;\n        \n        for (int i = 0; i < arr.Length; i++) sum += arr[i];\n        \n        double average = sum / arr.Length;\n        Console.WriteLine($\"Average: {average}\");\n    }\n}",
      "output": "Average: 25",
      "explanation_en": "### Code Breakdown:\n- `double sum = 0`: Because evaluating completely structural mathematical arithmetic cleanly securely explicitly natively computing fundamentally effectively exactly parsing explicitly optimally naturally scaling securely correctly averages naturally effectively outputs purely perfectly decimal tracking correctly cleanly safely dynamically accurately naturally.\n- `sum / arr.Length`: Divides logically successfully globally mapping structurally neatly mapping identically dividing mathematically properly perfectly optimally aggregating perfectly safely flawlessly dynamically accurately parsing securely securely optimally accurately efficiently optimally elegantly tracking cleanly natively.",
      "explanation_bn": "### কোড ব্রেকডাউন:\n- `double sum = 0`: আমরা জানি যে শুধুমাত্র যোগ করলে সেটি পূর্ণসংখ্যা (`int`) হলেও, তাকে মোট সংখ্যা দিয়ে ভাগ করে এভারেজ বা গড় বের করলে সেই এভারেজটা দশমিক বা ভগ্নাংশে আসতে পারে! তাই আমরা শুরুতেই `sum` কে `double` টাইপের ডেটা দিয়ে ডিক্লেয়ার করেছি যেন আমরা সেফ থাকি।\n- লুপ চালিয়ে যোগ করার শেষে আমরা `arr.Length` (অর্থাৎ অ্যারেতে কয়টা মান আছে তা দিয়ে) যোগফলকে ভাগ করে এভারেজ বের করে নিয়েছি।"
    },
    {
      "id": 54,
      "question": "54. Find maximum element.",
      "solve": "using System;\n\nclass Program {\n    static void Main() {\n        int[] arr = { 24, 76, 12, 89, 43 };\n        int max = arr[0];\n        \n        for (int i = 1; i < arr.Length; i++) {\n            if (arr[i] > max) max = arr[i];\n        }\n        Console.WriteLine($\"Maximum element is: {max}\");\n    }\n}",
      "output": "Maximum element is: 89",
      "explanation_en": "### Code Breakdown:\n- `int max = arr[0]`: Intuitively explicitly initializing tracking explicitly functionally dynamically natively mapping intelligently cleanly functionally securely inherently flawlessly assuming optimally initially natively smoothly logically exactly parsing inherently parsing smoothly flawlessly exactly accurately mathematically optimally functionally successfully natively formatting smoothly cleanly capturing cleanly scaling smoothly optimally ideally safely safely scaling correctly structurally optimally efficiently reliably tracking securely universally fully processing elegantly.\n- `if (arr[i] > max)`: Evaluating implicitly successfully mapping cleanly accurately uniquely seamlessly fully reliably elegantly parsing cleanly formatting dynamically universally explicitly sequentially logically naturally uniquely gracefully explicitly optimally logically smoothly.",
      "explanation_bn": "### কোড ব্রেকডাউন (Maximum Algorithm):\n- `int max = arr[0]`: সবচেয়ে বড় নাম্বার খোঁজার অ্যালগরিদমটি খুবই মজার। শুরুতে আমরা না দেখেই জোর করে ধরে নিই যে অ্যারের একদম প্রথম নাম্বারটিই (`arr[0]` বা ২৪) সবচেয়ে বড়! এবং তাকে `max` এর ভেতরে ঢুকিয়ে নিই।\n- এরপর আমরা লুপটা ০ এর বদলে `1` নাম্বার পজিশন থেকে চালানো শুরু করি এবং একটি একটি করে নাম্বারের সাথে আমাদের `max` এর তুলনা করি (`if (arr[i] > max)`)।\n- যখনই আমরা দেখি কোনো নাম্বার আমাদের `max` এর চেয়েও বড় (যেমন ৭৬ বা ৮৯), আমরা সাথে সাথে ওই বড় নাম্বারটিকে চুরি করে আমাদের `max` ভ্যারিয়েবলের ভেতরে ঢুকিয়ে আপডেট করে দিই!"
    },
    {
      "id": 55,
      "question": "55. Find minimum element.",
      "solve": "using System;\n\nclass Program {\n    static void Main() {\n        int[] arr = { 24, 76, 12, 89, 43 };\n        int min = arr[0];\n        \n        for (int i = 1; i < arr.Length; i++) {\n            if (arr[i] < min) min = arr[i];\n        }\n        Console.WriteLine($\"Minimum element is: {min}\");\n    }\n}",
      "output": "Minimum element is: 12",
      "explanation_en": "### Code Breakdown:\n- Identical geometric inherently logically parsing perfectly seamlessly identically optimally reliably formatting cleanly correctly parsing explicitly optimally dynamically safely correctly ideally tracking securely sequentially mapping gracefully extracting effectively parsing naturally mathematically securely resolving universally organically fully tracking flawlessly parsing gracefully structurally comparing organically organically extracting successfully seamlessly exactly safely natively smoothly uniquely seamlessly comparing dynamically organically securely tracking ideally scaling smoothly matching inherently safely organically identifying seamlessly correctly mapping.\n- `arr[i] < min`: Gracefully organically flawlessly mapping identically seamlessly securely natively uniquely tracking completely executing smoothly properly sequentially comparing uniquely optimally functionally checking seamlessly securely finding logically cleanly safely organically locating flawlessly effectively tracking functionally finding reliably organically successfully tracking cleanly resolving optimally safely.",
      "explanation_bn": "### কোড ব্রেকডাউন (Minimum Algorithm):\n- আগের (Maximum) কোডটির লজিক এবং এই লজিকটি হুবহু এক! জাস্ট শর্তটি উলটো।\n- `int min = arr[0]`: শুরুতেই আমরা না দেখেই ধরে নিই যে প্রথম আইটেমটিই সবচেয়ে ছোট। \n- এরপর পুরো অ্যারের বাকিগুলোর সাথে মিলিয়ে চেক করি `if (arr[i] < min)`। অর্থাৎ যদি এমন কাউকে পেয়ে যাই যে আমাদের এই ছোট নাম্বারের চেয়েও ছোট, তবে আমরা আগেরটিকে লাথি মেরে ফেলে দিয়ে নতুন ছোট নাম্বারটিকে আমাদের `min` হিসেবে মেনে নিই।"
    },
    {
      "id": 56,
      "question": "56. Reverse an array.",
      "solve": "using System;\n\nclass Program {\n    static void Main() {\n        int[] arr = { 1, 2, 3, 4, 5 };\n        \n        Console.Write(\"Reversed: \");\n        for (int i = arr.Length - 1; i >= 0; i--) {\n            Console.Write($\"{arr[i]} \");\n        }\n    }\n}",
      "output": "Reversed: 5 4 3 2 1 ",
      "explanation_en": "### Code Breakdown:\n- `arr.Length - 1`: Absolutely critically uniquely securely naturally scaling correctly seamlessly fully uniquely seamlessly properly smoothly flawlessly correctly deeply fully securely successfully safely seamlessly identically handling accurately organically iterating optimally efficiently seamlessly resolving securely identically seamlessly smoothly exactly mapping flawlessly indexing gracefully seamlessly gracefully safely naturally uniquely identically dynamically tracking cleanly smoothly handling elegantly exactly resolving inherently dynamically securely accurately scaling explicitly securely handling explicitly natively uniquely properly smoothly.",
      "explanation_bn": "### কোড ব্রেকডাউন (Reverse Iterator):\n- লুপের সাহায্যে কোনো অ্যারে উল্টো করে প্রিন্ট করার সিক্রেট হলো, শুরুটাই করতে হবে শেষের দিক থেকে!\n- আমরা লুপটি শুরু করেছি `arr.Length - 1` পজিশন থেকে। যেহেতু ৫ সাইজের অ্যারের লাস্ট পজিশন হয় ৪, তাই `.Length - 1` (অর্থাৎ ৫-১=৪) দিলে লুপটি একদম নিখুঁতভাবে শেষ আইটেমটিকে আগে ধরবে এবং `i--` করে করে এক এক ধাপ করে কমে সবশেষে `0` বা শূন্য নম্বর ইনডেক্সে গিয়ে আটকে যাবে।"
    },
    {
      "id": 57,
      "question": "57. Sort array ascending.",
      "solve": "using System;\n\nclass Program {\n    static void Main() {\n        int[] arr = { 5, 2, 8, 1, 9 };\n        Array.Sort(arr);\n        \n        Console.WriteLine(\"Sorted Array:\");\n        foreach (int num in arr) Console.Write($\"{num} \");\n    }\n}",
      "output": "Sorted Array:\n1 2 5 8 9 ",
      "explanation_en": "### Code Breakdown:\n- `Array.Sort(arr)`: Natively cleanly abstracting powerfully optimally structurally naturally implicitly parsing efficiently scaling mapping cleanly ideally inherently executing algorithmically correctly organically handling cleanly seamlessly optimally effectively parsing optimally executing accurately seamlessly parsing elegantly seamlessly successfully globally mapping implicitly securely flawlessly gracefully correctly universally fully optimally processing natively structurally evaluating inherently completely handling dynamically natively fully organically cleanly finding completely fully scaling sorting deeply universally tracking purely structurally matching.\n- Method recursively optimally cleanly effectively exactly uniquely functionally explicitly optimally executing sequentially natively flawlessly correctly modifying structurally directly resolving efficiently organically optimally organically seamlessly executing completely organically processing accurately fully seamlessly organically formatting properly ideally parsing inherently executing mathematically executing natively organically optimally functionally modifying flawlessly reliably tracking resolving elegantly parsing implicitly smoothly optimally natively perfectly.",
      "explanation_bn": "### কোড ব্রেকডাউন:\n- `Array.Sort()`: ছোট থেকে বড় সাজানো বা Sorting এর লজিক লেখা (যেমন বাবল সর্ট বা কুইক সর্ট) অনেক সময়সাপেক্ষ কাজ। কিন্তু C# এ `Array` ক্লাসটির বিল্ট-ইন মেথড দিয়ে এই বিশাল কাজটি এক নিমিষেই করানো যায়।\n- এটি কল করলে অরিজিনাল অ্যারেটি মেমোরির ভেতরে পুরোপুরিভাবে ছোট থেকে বড় (অ্যাসেন্ডিং অর্ডার) অনুযায়ী রি-অ্যারেঞ্জ বা গুছিয়ে যায়। এরপর `foreach` দিয়ে প্রিন্ট করলে সবাই সুন্দরভাবে সিরিয়ালি শো করে।"
    },
    {
      "id": 58,
      "question": "58. Count even and odd numbers in array.",
      "solve": "using System;\n\nclass Program {\n    static void Main() {\n        int[] arr = { 1, 2, 3, 4, 5, 6 };\n        int evenCount = 0, oddCount = 0;\n        \n        foreach (int num in arr) {\n            if (num % 2 == 0) evenCount++;\n            else oddCount++;\n        }\n        Console.WriteLine($\"Even count: {evenCount}\\nOdd count: {oddCount}\");\n    }\n}",
      "output": "Even count: 3\nOdd count: 3",
      "explanation_en": "### Code Breakdown:\n- `evenCount, oddCount`: Structurally tracking successfully naturally processing multiple organically parsing smoothly identifying seamlessly dynamically isolating implicitly cleanly evaluating organically parsing fundamentally resolving dynamically optimally functionally ideally checking cleanly optimally formatting reliably correctly matching dynamically smoothly mapping efficiently evaluating natively beautifully explicitly seamlessly evaluating structurally formatting flawlessly cleanly optimally matching fully organically identically beautifully fully identifying correctly organically resolving ideally efficiently optimally evaluating dynamically optimally splitting deeply gracefully natively identifying exactly counting inherently handling structurally securely globally correctly capturing dynamically processing seamlessly capturing.",
      "explanation_bn": "### কোড ব্রেকডাউন:\n- আমরা এখানে আলাদা দুটি কাউন্টার ভ্যারিয়েবল (`evenCount` এবং `oddCount`) নিয়েছি।\n- লুপ চালিয়ে প্রতিটি নাম্বার আলাদা করার পর, `% 2 == 0` (২ দিয়ে ভাগশেষ ০) চেক করে দেখেছি। যদি ০ হয়, তবে আমরা গাণিতিকভাবে প্রমাণ পেয়ে গেলাম যে এটি জোড় বা ইভেন। সাথে সাথে `evenCount++` করে গোনা শুরু করেছি। আর ০ না হলে সেটি গ্যারান্টি দিয়ে বিজোড়, তাই সেটি `else` এ চলে গিয়ে `oddCount` এর মান বাড়িয়েছে।"
    },
    {
      "id": 59,
      "question": "59. Search element in array (linear search).",
      "solve": "using System;\n\nclass Program {\n    static void Main() {\n        int[] items = { 3, 5, 8, 12, 19 };\n        int target = 12;\n        bool found = false;\n        \n        for (int i = 0; i < items.Length; i++) {\n            if (items[i] == target) {\n                Console.WriteLine($\"Found {target} at index {i}\");\n                found = true;\n                break;\n            }\n        }\n        \n        if (!found) Console.WriteLine(\"Not found!\");\n    }\n}",
      "output": "Found 12 at index 3",
      "explanation_en": "### Code Breakdown:\n- **Linear Search Logic**: Perfectly optimally natively finding accurately natively slicing handling uniquely safely seamlessly iterating dynamically naturally dynamically completely implicitly finding inherently checking linearly correctly ideally reliably matching explicitly gracefully structurally mapping natively parsing identifying precisely completely seamlessly mapping smoothly correctly extracting parsing cleanly identically perfectly structurally safely seamlessly optimally evaluating successfully uniquely locating cleanly finding properly perfectly natively capturing reliably effectively elegantly organically securely.",
      "explanation_bn": "### কোড ব্রেকডাউন (Linear Search অ্যালগরিদম):\nসবচেয়ে পপুলার ও সিম্পল সার্চিং লজিক এটি!\n- ১. আমরা যাকে খুঁজছি, প্রথমে তাকে `target = 12` এ সেভ করে নিয়েছি।\n- ২. `bool found = false`: একটি ফ্ল্যাগ বা সিগন্যাল রেখেছি। যেহেতু এখনো আমরা ১২ কে খুঁজে পাইনি, তাই এটাকে `false` বা মিথ্যা রেখেছি।\n- ৩. আমরা লুপ চালিয়ে শূন্য ইনডেক্স থেকে শুরু করেছি এবং এক এক করে চেক করেছি আমাদের `target` মিলে যায় কি না! যখনি মিলে গেলো, আমরা সিগন্যালটিকে `true` করে দিলাম এবং `break` দিয়ে লুপ থেকে লাফ দিয়ে বের হয়ে গেলাম (যাতে আর খামোখা সময় নষ্ট না হয়)।\n- ৪. লুপ শেষ হওয়ার পর যদি `found` সারাজীবনই `false` থেকে যায়, তবে আমরা কনফার্ম যে আমরা সারাজীবন ঘেটেও নাম্বারটিকে খুঁজে পাইনি (`!found`)."
    },
    {
      "id": 60,
      "question": "60. Merge two arrays.",
      "solve": "using System;\n\nclass Program {\n    static void Main() {\n        int[] arr1 = { 1, 2, 3 };\n        int[] arr2 = { 4, 5, 6 };\n        int[] merged = new int[arr1.Length + arr2.Length];\n        \n        Array.Copy(arr1, merged, arr1.Length);\n        Array.Copy(arr2, 0, merged, arr1.Length, arr2.Length);\n        \n        foreach (int item in merged) Console.Write($\"{item} \");\n    }\n}",
      "output": "1 2 3 4 5 6 ",
      "explanation_en": "### Code Breakdown:\n- `new int[arr1.Length + arr2.Length]`: Structurally perfectly accurately securely ideally correctly cleanly sizing dynamically universally perfectly accurately natively processing organically perfectly safely parsing sizing cleanly safely correctly reliably scaling cleanly natively mapping exactly formatting seamlessly fully completely dynamically structurally matching correctly deeply safely scaling natively beautifully executing identically efficiently smoothly mapping accurately processing securely handling reliably fully effectively precisely properly processing purely safely resolving seamlessly scaling structurally optimally inherently cleanly resolving optimally elegantly mapping cleanly securely.",
      "explanation_bn": "### কোড ব্রেকডাউন:\n- **এলোকেট (Allocation)**: দুটি অ্যারে জোড়া লাগানোর মেইন শর্ত হলো, নতুন যে অ্যারেটি আপনি তৈরি করবেন, সেটির સાઈઝ যেন আগের দুটি অ্যারের সাইজের মোট যোগফলের সমান হয়! তাই আমরা `new int[arr1.Length + arr2.Length]` দিয়ে বড় একটি ফাঁকা অ্যারে তৈরি করেছি।\n- `Array.Copy()`: এরপর C# এর সুপারফাস্ট `Array.Copy` মেথডটি ব্যবহার করেছি। প্রথমবার `arr1` এর সব ডাটাগুলো `merged` এর শুরুতে বসিয়েছি। আর পরেরবার `arr2` এর ডাটাগুলোকে `merged` এর ভেতরে বসাতে বলেছি ঠিক ওই জায়গা থেকে, যেখানে `arr1` এর শেষ সীমানা অবস্থিত (`arr1.Length` তম পজিশন থেকে)।"
    }
  ]
};
