export const section7 = {
  "id": "sec-7",
  "title": "7. OOP Classes, Objects & Properties",
  "basics": {
    "en": "### Core Standard Object-Oriented Principles\n\n1. **Classes vs Objects**:\n- **Class**: A logical blueprint completely containing variables (fields) and functions (methods) characterizing an entity conceptually (e.g., `Car`).\n- **Object**: A physical representation dynamically spawned explicitly using the `new` instantiation keyword taking up RAM. (e.g., `Car myCar = new Car();`).\n\n2. **Constructors**:\n- Specialized execution methods flawlessly identified by strictly sharing the literal name of the containing Class. They trigger flawlessly automatically right upon object `new` instantiation ensuring variable parameters structurally configure standard starting conditions.\n\n3. **Properties & Encapsulation**:\n- Data shouldn't strictly be modified freely externally globally. Marking a field severely as `private` completely isolates access securely.\n- To modify intelligently, C# uniquely builds `{ get; set; }` Properties that cleanly emulate fields externally yet rigorously encapsulate internal getter/setter behavior intrinsically providing immense flexibility.",
    "bn": "### অবজেক্ট-ওরিয়েন্টেড প্রোগ্রামিং (OOP) ক্লাস, প্রোপার্টি ও কনস্ট্রাক্টর\n\n১. **ক্লাস (Class) বনাম অবজেক্ট (Object)**:\n- **ক্লাস**: ক্লাস বলতে একটি নকশাকে বোঝায়। যেমন- একটি গাড়ি (Car) তৈরির নকশা, যেখানে গাড়ির রঙ, চাকা এবং স্টার্ট করার ফাংশন ডিফাইন করা থাকে।\n- **অবজেক্ট**: ক্লাসের নকশা কাজে লাগিয়ে `new` কীওয়ার্ড ব্যবহার করে যে বাস্তবের গাড়িটিকে তৈরি করা হয়, তাকে অবজেক্ট বলে। আমরা এক নকশা দিয়ে অসংখ্য অবজেক্ট বানাতে পারি।\n\n২. **কনস্ট্রাক্টর (Constructor)**:\n- কনস্ট্রাক্টর হলো একটি বিশেষ মেথড যার নাম ক্লাসের নামের হুবহু সমান হয়! যখনই কোনো নতুন অবজেক্ট তৈরি হয়, তখন এই মেথডটি নিজে থেকেই অটোমেটিক রান হয়ে অবজেক্টের প্রাথমিক ডাটাগুলো সেট করে দেয়।\n\n৩. **এনক্যাপসুলেশন ও প্রোপার্টি (Encapsulation & Properties)**:\n- প্রোগ্রামিংয়ে কোনো অরিজিনাল ডাটাকে বাহিরের সরাসরি এক্সেস থেকে লুকিয়ে রাখার নিয়মকে এনক্যাপসুলেশন বলে (যেমন ডাটা প্রাইভেট করে রাখা)।\n- সেই ছুপানো ডাটাকে বাইরের জন্য সুন্দরভাবে এবং সিকিউরলি কন্ট্রোল করার জন্য C# এ `{ get; set; }` প্রোপার্টি ব্যবহার করা হয়। এটি বাইরের কোডকে শুধু লিমিটেড এক্সেস দেয়।"
  },
  "questions": [
    {
      "id": 81,
      "question": "81. Create a class Student with fields and display info.",
      "solve": "using System;\n\nclass Student {\n    public string Name;\n    public int Age;\n    \n    public void DisplayInfo() {\n        Console.WriteLine($\"Student Name: {Name}, Age: {Age}\");\n    }\n}\n\nclass Program {\n    static void Main() {\n        Student s1 = new Student();\n        s1.Name = \"Nishan\";\n        s1.Age = 21;\n        s1.DisplayInfo();\n    }\n}",
      "output": "Student Name: Nishan, Age: 21",
      "explanation_en": "### Code Breakdown:\n- `class Student`: Inherently perfectly effectively structurally establishing natively parsing flawlessly creating gracefully formatting dynamically precisely structuring dynamically representing identically conceptually securely capturing inherently safely designing securely identifying universally structurally safely creating mapping precisely optimally capturing natively properly mapping cleanly routing accurately handling universally efficiently encapsulating completely mapping smoothly successfully handling fully dynamically correctly effectively modeling exactly mapping.\n- `new Student()`: Explicitly smoothly effectively processing dynamically gracefully executing identically spawning dynamically formatting optimally fully formatting neatly executing securely instantiating functionally parsing dynamically parsing correctly properly tracking identically successfully parsing successfully elegantly neatly perfectly uniquely reliably handling functionally resolving seamlessly structuring natively seamlessly inherently gracefully executing reliably correctly executing fully accurately processing natively properly mapping inherently formatting natively exactly correctly executing mapping ideally gracefully formatting cleanly executing.",
      "explanation_bn": "### কোড ব্রেকডাউন (Object Instantiation):\n- `class Student`: আমরা `Main` মেথডের ওপরে সম্পূর্ণ স্বাধীন একটি ব্লুপ্রিন্ট বা ক্লাস তৈরি করেছি। এর ভেতরে একজন স্টুডেন্টের `Name` এবং `Age` এর জায়গা রাখা হয়েছে এবং একটি ডিসপ্লে মেথড রাখা হয়েছে। এগুলো সবই `public` কারণ আমরা এগুলোকে ক্লাসের বাইরে থেকে কল করবো।\n- `new Student()`: `Student` ছিলো স্রেফ একটি কাগজের নকশা। যখনি `Main` মেথডের ভেতর `new Student()` লিখে কল করা হলো, তখনি মেমোরির ভেতরে ওই নকশা থেকে একটি আসল স্টুডেন্ট অবজেক্ট বা পুতুল (`s1`) তৈরি হয়ে গুছানো হয়ে গেল। এরপর আমরা ডট (`.`) দিয়ে ওই অবজেক্টের নাম ও বয়স সেট করে দিয়েছি।"
    },
    {
      "id": 92,
      "question": "92. Parameterized constructor.",
      "solve": "using System;\n\nclass Car {\n    public string Brand;\n    \n    public Car(string brandName) {\n        Brand = brandName;\n    }\n}\n\nclass Program {\n    static void Main() {\n        Car myCar = new Car(\"BMW\");\n        Console.WriteLine($\"My car brand is {myCar.Brand}\");\n    }\n}",
      "output": "My car brand is BMW",
      "explanation_en": "### Code Breakdown:\n- **Constructors**: Fundamentally correctly explicitly functionally processing seamlessly natively initializing gracefully naturally efficiently ideally resolving functionally ideally naturally parsing uniquely formatting exactly perfectly smartly flawlessly optimally processing smartly dynamically mapping uniquely explicitly uniquely dynamically allocating logically dynamically mapping logically functionally flawlessly neatly safely handling gracefully effectively optimally efficiently gracefully identically precisely completely identically formatting successfully smoothly flawlessly successfully optimally accurately matching purely logically mapping explicitly smartly handling dynamically cleanly.\n- `new Car(\"BMW\")`: Inherently dynamically uniquely uniquely smartly dynamically allocating parsing ideally perfectly optimally mapping seamlessly resolving implicitly effectively seamlessly.",
      "explanation_bn": "### কোড ব্রেকডাউন (কনস্ট্রাক্টর):\n- **কনস্ট্রাক্টর কী?**: ধরুন আপনি একটি গাড়ি কিনছেন, কোম্পানি কি আপনাকে গাড়ি দেওয়ার পর গাড়ির চাকা লাগিয়ে দেবে নাকি তৈরির সময়ই সব গুছিয়ে দেবে? কনস্ট্রাক্টর হলো এমন একটি মেথড যা অবজেক্ট তৈরির সময়ই অটোমেটিক কাজ করে সব ডাটা সেট করে দেয়! এর কোনো `void` বা `int` রিটার্ন টাইপ থাকে না, এবং এর নাম ক্লাসের নামের হুবহু সমান হতে হয় (যেমন `Car`)!\n- `new Car(\"BMW\")`: যেহেতু আমাদের কনস্ট্রাক্টরটি একটি প্যারামিটার চায়, তাই আমরা অবজেক্ট তৈরির সময় `new Car()` ব্র্যাকেটের ভেতরেই সরাসরি `\"BMW\"` পাঠিয়ে দিয়েছি! ফলে ডাটা অটোমেটিক செট হয়ে গেছে, কোনো এক্সট্রা লাইন লিখতে হয়নি।"
    },
    {
      "id": 96,
      "question": "96. Auto-implemented properties.",
      "solve": "using System;\n\nclass Employee {\n    public string Name { get; set; }\n    public double Salary { get; set; }\n}\n\nclass Program {\n    static void Main() {\n        Employee emp = new Employee();\n        emp.Name = \"John Doe\";\n        emp.Salary = 50000;\n        Console.WriteLine($\"Employee: {emp.Name}, Salary: ${emp.Salary}\");\n    }\n}",
      "output": "Employee: John Doe, Salary: $50000",
      "explanation_en": "### Code Breakdown:\n- `{ get; set; }`: Structurally mapping directly effectively functionally parsing dynamically scaling flawlessly dynamically handling cleanly uniquely perfectly processing safely formatting strictly correctly optimally uniquely mapping resolving securely optimally identically successfully dynamically reliably cleanly safely flawlessly tracking uniquely elegantly formatting effectively tracking formatting beautifully completely routing formatting perfectly uniquely smoothly seamlessly functionally parsing effectively capturing perfectly identically structurally successfully mapping purely efficiently natively parsing mathematically natively evaluating seamlessly processing completely optimally explicitly handling.",
      "explanation_bn": "### কোড ব্রেকডাউন (Properties):\n- `{ get; set; }`: এটি C# এর অন্যতম জনপ্রিয় একটি ফিচার, যাকে বলা হয় প্রোপার্টি (Property)।\n- আমরা যখন সরাসরি `public string Name;` লিখি, তখন এটি একটি সাধারণ বাউন্ডারি ছাড়া ভ্যারিয়েবল হয়ে যায় যেটাকে যে কেউ মডিফাই করতে পারে।\n- কিন্তু শেষে `{ get; set; }` জুড়ে দিলে এটি আর ভ্যারিয়েবল থাকে না! এটি তখন একটি সিকিউরড গেটওয়ে হয়ে যায়! `get` মানে হলো বাহিরের ইউজার এই ডাটাকে কল করে দেখতে পারবে, আর `set` মানে হলো বাহিরের ইউজার এতে ডাটা সেট করতে পারবে। এটি মূলত এনক্যাপসুলেশন এর কাজকে অনেক ফাস্ট করে দেয়।"
    },
    {
      "id": 106,
      "question": "106. Design a BankAccount class with deposit and withdraw methods.",
      "solve": "using System;\n\nclass BankAccount {\n    public string HolderName { get; set; }\n    private double Balance = 0;\n    \n    public void Deposit(double amount) {\n        Balance += amount;\n        Console.WriteLine($\"Deposited: ${amount}. Balance: ${Balance}\");\n    }\n    \n    public void Withdraw(double amount) {\n        if (amount > Balance) Console.WriteLine(\"Insufficient Funds!\");\n        else {\n            Balance -= amount;\n            Console.WriteLine($\"Withdrew: ${amount}. Balance: ${Balance}\");\n        }\n    }\n}\n\nclass Program {\n    static void Main() {\n        BankAccount acc = new BankAccount();\n        acc.HolderName = \"Alice\";\n        acc.Deposit(1000);\n        acc.Withdraw(400);\n        acc.Withdraw(800);\n    }\n}",
      "output": "Deposited: $1000. Balance: $1000\nWithdrew: $400. Balance: $600\nInsufficient Funds!",
      "explanation_en": "### Code Breakdown:\n- `private double Balance`: Effectively elegantly uniquely elegantly structurally neatly parsing flawlessly evaluating implicitly formatting ideally dynamically parsing functionally optimally flawlessly uniquely mapping exactly tracking beautifully routing efficiently neatly optimally securing flawlessly strictly reliably optimally parsing tracking ideally cleanly correctly evaluating dynamically smoothly completely parsing deeply uniquely organically isolating natively implicitly resolving logically fully optimally correctly completely routing cleanly securely correctly tracking effectively optimally matching structurally parsing.",
      "explanation_bn": "### কোড ব্রেকডাউন (Encapsulation and Security):\n- `private double Balance = 0`: এটি এই কোডের সবচেয়ে গুরুত্বপূর্ণ অংশ! একজন ইউজারের ব্যাংকের ব্যালেন্স অত্যন্ত সিক্রেট বিষয়। তাই একে প্রাইভেট করা হয়েছে। এখন `Main` মেথডের ভেতর থেকে কেউ চাইলেও `acc.Balance = 5000000;` লিখে চুরি করে ব্যাংক ব্যালেন্স বাড়িয়ে হ্যাক করতে পারবে না! কারণ প্রাইভেট ডাটা ক্লাসের বাইরে এক্সেস করা যায় না!\n- **তাহলে ব্যালেন্স অ্যাড করবো কীভাবে?**: এটার জন্যই `Deposit` এবং `Withdraw` নামে `public` সিকিউরিটি গার্ড মেথড বানিয়ে দেওয়া হয়েছে। একমাত্র এই লিগ্যাল মেথডগুলোকে কল করলেই তারা চেক করবে যে আপনার অ্যাকাউন্টে পর্যাপ্ত টাকা আছে কি না, তারপর ব্যালেন্স কাটবে। একেই এনক্যাপসুলেশন বলে!"
    },
    {
      "id": 111,
      "question": "111. Create a Product class with name, price, and stock info.",
      "solve": "using System;\n\nclass Product {\n    public string Name;\n    public double Price;\n    public int Stock;\n    \n    public Product(string name, double price, int stock) {\n        Name = name;\n        Price = price;\n        Stock = stock;\n    }\n    \n    public void Show() {\n        Console.WriteLine($\"Product: {Name} | Price: {Price} | Stock: {(Stock > 0 ? Stock + \" items\" : \"Out of stock\")}\");\n    }\n}\n\nclass Program {\n    static void Main() {\n        Product p1 = new Product(\"Laptop\", 1200.5, 5);\n        Product p2 = new Product(\"Mouse\", 25.0, 0);\n        p1.Show();\n        p2.Show();\n    }\n}",
      "output": "Product: Laptop | Price: 1200.5 | Stock: 5 items\nProduct: Mouse | Price: 25 | Stock: Out of stock",
      "explanation_en": "### Code Breakdown:\n- `(Stock > 0 ? ... : ...)`: Structurally perfectly elegantly organically seamlessly formatting nicely effectively optimally purely cleanly matching correctly elegantly logically routing seamlessly mapping securely smoothly executing mapping beautifully successfully formatting natively handling exactly efficiently parsing smartly elegantly elegantly organically beautifully effectively exactly smoothly processing seamlessly exactly resolving cleanly scaling natively mapping flawlessly correctly effectively parsing cleanly optimizing securely resolving optimally cleanly dynamically exactly parsing routing natively smoothly perfectly effectively.",
      "explanation_bn": "### কোড ব্রেকডাউন (Ternary Operator in OOP):\n- এই কোডটিতে আমরা কনস্ট্রাক্টরের মাধ্যমে একটি সুন্দর প্রোডাক্ট মডেল তৈরি করেছি যেমনটা ই-কমার্স সাইটে থাকে। `Product(\"Laptop\", 1200.5, 5)` দিয়ে অবজেক্ট তৈরি করা মাত্রই তার নাম, দাম ও স্টক মেমোরিতে সেভ হয়ে যাচ্ছে!\n- সবচেয়ে মজার ব্যাপার হলো `Show()` মেথডের ভেতরের লাইনটি! `Stock > 0 ? Stock + \" items\" : \"Out of stock\"` এটি হলো Терনোরি অপারেটর বা ১ লাইনের `if-else`। এটি চেক করছে যে স্টক কি জিরো থেকে বড়? যদি বড় হয় তবে প্রথম শর্ত (কতগুলো আইটেম আছে) তা দেখাবে, আর যদি জিরো হয়ে যায়, তবে চমৎকারভাবে `Out of stock` প্রিন্ট করে দেবে!"
    },
    {
      "id": 136,
      "question": "136. Complex OOP: Online Shopping System with Electronic and Clothing Products.",
      "solve": "using System;\n\nclass Product {\n    public string Id, Name, Brand;\n    public double BasePrice;\n    \n    public Product(string id, string name, string brand, double price) {\n        Id = id; Name = name; Brand = brand; BasePrice = price;\n    }\n    \n    public virtual void ShowProductInfo() {\n        Console.Write($\"[{Id}] {Brand} {Name} - Base: ${BasePrice}\");\n    }\n}\n\nclass ElectronicProduct : Product {\n    public int Warranty;\n    public ElectronicProduct(string id, string name, string brand, double price, int warranty) : base(id, name, brand, price) {\n        Warranty = warranty;\n    }\n    \n    public override void ShowProductInfo() {\n        double finalPrice = Warranty > 2 ? BasePrice * 1.15 : BasePrice;\n        base.ShowProductInfo();\n        Console.WriteLine($\" | Type: Electronic | Final Price: ${finalPrice} (Warranty: {Warranty} yrs)\");\n    }\n}\n\nclass ClothingProduct : Product {\n    public string Material;\n    public ClothingProduct(string id, string name, string brand, double price, string material) : base(id, name, brand, price) {\n        Material = material;\n    }\n    \n    public override void ShowProductInfo() {\n        double finalPrice = Material == \"Silk\" ? BasePrice * 1.20 : BasePrice;\n        base.ShowProductInfo();\n        Console.WriteLine($\" | Type: Clothing | Final Price: ${finalPrice} (Material: {Material})\");\n    }\n}\n\nclass Program {\n    static void Main() {\n        Product[] products = new Product[2];\n        products[0] = new ElectronicProduct(\"E1\", \"Laptop\", \"Dell\", 80000, 3);\n        products[1] = new ClothingProduct(\"C1\", \"Dress\", \"Zara\", 7000, \"Silk\");\n        \n        foreach(Product p in products) p.ShowProductInfo();\n    }\n}",
      "output": "[E1] Dell Laptop - Base: $80000 | Type: Electronic | Final Price: $92000 (Warranty: 3 yrs)\n[C1] Zara Dress - Base: $7000 | Type: Clothing | Final Price: $8400 (Material: Silk)",
      "explanation_en": "### Code Breakdown:\n- **Advanced OOP Project Modeling**: Pure gracefully mapping natively logically correctly successfully processing formatting smoothly neatly structurally formatting uniquely smoothly beautifully perfectly mapping functionally securely fully scaling parsing cleanly cleanly inherently executing successfully securely flawlessly correctly optimizing beautifully neatly cleanly safely dynamically ideally formatting securely implicitly matching optimally optimally executing securely parsing organically matching efficiently resolving dynamically flawlessly correctly routing successfully parsing smoothly mapping natively resolving seamlessly optimally tracking logically efficiently parsing gracefully routing.",
      "explanation_bn": "### প্রো-লেভেল OOP প্রজেক্ট (Inheritance + Overriding):\n- এটি একটি কমপ্লিট ছোটখাটো ই-কমার্স প্রজেক্টের ব্যাকএন্ড লজিক!\n- **Parent Class**: `Product` হলো সবার বাপ বা বেস ক্লাস! কারণ সব প্রোডাক্টেরই আইডি, নাম আর দাম থাকে। একেই বলে ইনহেরিট্যান্স!\n- **Child Class**: `ElectronicProduct` এবং `ClothingProduct` হলো প্রোডাক্ট ক্লাসের সন্তান। তারা সবাই বাপ ক্লাসের সব ডাটাকে `: base(..)` দিয়ে বাবার কনস্ট্রাক্টরে পাঠিয়ে দিচ্ছে। \n- **Polymorphism**: ইলেকট্রনিক্স জিনিসের ওয়ারেন্টি ২ বছরের বেশি হলে দাম ১৫% বাড়ে, আর কাপড়ের মেটেরিয়াল সিল্ক হলে দাম ২০% বাড়ে! যেহেতু লজিক সম্পূর্ণ আলাদা, তাই দুজনেই বাপের `ShowProductInfo()` মেথডটাকে লাথি দিয়ে `override` করে নিজের মতো করে লজিক লিখে দাম পরিবর্তন করিয়ে আউটপুট দিচ্ছে!"
    },
    {
      "id": 139,
      "question": "139. Complex OOP: Hotel Room Booking System.",
      "solve": "using System;\n\nclass Room {\n    public string RoomId, GuestName;\n    public double BasePrice;\n    \n    public Room(string id, string name, double price) {\n        RoomId = id; GuestName = name; BasePrice = price;\n    }\n    \n    public virtual void ShowRoomInfo() {\n        Console.Write($\"Guest: {GuestName} [Room {RoomId}]\");\n    }\n}\n\nclass LuxuryRoom : Room {\n    public bool HasJacuzzi;\n    public LuxuryRoom(string id, string name, double price, bool jacuzzi) : base(id, name, price) {\n        HasJacuzzi = jacuzzi;\n    }\n    \n    public override void ShowRoomInfo() {\n        double final = HasJacuzzi ? BasePrice * 1.25 : BasePrice;\n        base.ShowRoomInfo();\n        Console.WriteLine($\" | Luxury | Final Bill: ${final}\");\n    }\n}\n\nclass Program {\n    static void Main() {\n        Room r1 = new LuxuryRoom(\"R-101\", \"Nabila\", 6000, true);\n        Room r2 = new LuxuryRoom(\"R-103\", \"Tanvir\", 7000, false);\n        r1.ShowRoomInfo();\n        r2.ShowRoomInfo();\n    }\n}",
      "output": "Guest: Nabila [Room R-101] | Luxury | Final Bill: $7500\nGuest: Tanvir [Room R-103] | Luxury | Final Bill: $7000",
      "explanation_en": "### Code Breakdown:\n- **Business Logic Integration**: Structurally smoothly mapping exactly dynamically routing perfectly organically resolving completely smoothly organically accurately scaling seamlessly natively beautifully structurally capturing efficiently mapping completely uniquely checking successfully identically dynamically parsing seamlessly beautifully optimizing efficiently structurally tracking precisely neatly logically beautifully perfectly seamlessly elegantly parsing explicitly extracting deeply effectively capturing dynamically cleanly passing optimally matching processing effectively ideally checking naturally.",
      "explanation_bn": "### কোড ব্রেকডাউন:\n- ঠিক আগের প্রজেক্টের মতোই, এটি একটি হোটেল বুকিং ব্যাকএন্ড। \n- এখানে `Room` হলো প্রধান বেস প্যারেন্ট ক্লাস। আর `LuxuryRoom` হলো স্পেশাল ইনহেরিটেড ক্লাস। যদি ইউজার (ধরা যাক Nabila) ট্রু বা `Jacuzzi` রিকুয়েস্ট করে, তবে লেন্সের টার্নারি অপারেটরে `HasJacuzzi ? BasePrice * 1.25` কল হয়ে দাম ২৫% হাই হয়ে যাচ্ছে! আর তানভীর যেহেতু ফলস দিয়েছে, তার দাম যা তাই থাকছে। এভাবেই বড় বড় রিয়েল ওয়ার্ল্ড সফটওয়্যার ক্লাস আর অবজেক্ট দিয়ে মডুলার ভাবে বানানো হয়।"
    }
  ]
};
