export const section8 = {
  "id": "sec-8",
  "title": "8. Inheritance & Polymorphism",
  "basics": {
    "en": "### Inheritance, Polymorphism & Deep OOP\n\n1. **Inheritance Sub-Classing (`:`)**:\n- Directly extracting repetitive traits outwards into a central generic `Base Class` (e.g., `Vehicle`) securely allowing granular Sub-Classes (`Car`, `Bike`) to perfectly assume inherited fields structurally. Signified fundamentally utilizing the colon `:` delimiter strictly preventing manual code retyping.\n\n2. **Base Constructors Mapping (`base`)**:\n- Inherited classes execute base constructors absolutely first natively. If a Parent mathematically requires initial constructor arguments rigidly, its structurally reliant Child intrinsically MUST handpass those arguments up using `: base(...)` immediately atop its constructor signature mapping.\n\n3. **Polymorphic Method Overriding (`virtual` / `override`)**:\n- **Virtual**: Applied firmly onto a Base Class method dictating mathematically: \"Child classes genuinely have exclusive permission to radically replace my core logic if wanted\".\n- **Override**: Executed strictly upon a Child representing precisely: \"I inherently override my Parent's generic virtual method actively prioritizing my custom behavior uniquely internally\".",
    "bn": "### ইনহেরিট্যান্স, পলিমরফিজম এবং আউটপুট চেইনিং\n\n১. **ইনহেরিট্যান্স (Inheritance `:`)**:\n- এক ক্লাসের সমস্ত বৈশিষ্ট্য (Data & Methods) বিনা পরিশ্রমে অন্য আরেকটি ক্লাসে হুবহু নিয়ে আসার পদ্ধতিকে ইনহেরিট্যান্স বলে। যেখান থেকে নেয়া হয় তাকে Base Class এবং যে ক্লাস বৈশিষ্টগুলো গ্রহণ করে তাকে Derived/Child ক্লাস বলে। এটি C# এ ক্লোন বা `:` চিহ্ন দিয়ে করা হয়।\n\n২. **বেস কনস্ট্রাক্টর (`base`)**:\n- যখন চাইল্ড ক্লাসের কোনো অবজেক্ট তৈরি হয়, তখন সবার আগে অটোমেটিক্যালি তার প্যারেন্ট ক্লাসের কনস্ট্রাক্টর কল হয়ে যায়। প্যারেন্টের কনস্ট্রাক্টরে যদি কোনো প্যারামিটার দিতে হয়, তবে চাইল্ড ক্লাসকে `: base(...)` দিয়ে সেটিকে হ্যান্ডওভার করতে বাধ্য থাকতে হয়।\n\n৩. **পলিমরফিজম এবং ওভাররাইডিং (Polymorphism `virtual/override`)**:\n- পলিমরফিজম মানে বহুরূপিতা। অর্থাৎ একই ফাংশন বিভিন্ন অবজেক্টে ভিন্ন ভিন্ন রূপ ধারণ করবে।\n- প্যারেন্ট ক্লাসের মেথডের আগে `virtual` কীওয়ার্ড দিলে তা চাইল্ড ক্লাসের জন্য পরিবর্তনের পারমিশন দিয়ে দেয়।\n- চাইল্ড ক্লাসে সেই মেথডের আগে `override` কীওয়ার্ড ব্যবহার করে সম্পূর্ণ নতুন লজিক লেখা যায়, যা প্যারেন্ট ক্লাসের আচরণকে অগ্রাহ্য করে নিজের আচরণ প্রকাশ করে।"
  },
  "questions": [
    {
      "id": 126,
      "question": "126. Animal Sound System (Inheritance). Dog and Cat inherit Animal.",
      "solve": "using System;\n\nclass Animal {\n    public virtual void MakeSound() {\n        Console.WriteLine(\"Animal makes a general sound\");\n    }\n}\n\nclass Dog : Animal {\n    public override void MakeSound() {\n        Console.WriteLine(\"Dog barks: Woof Woof!\");\n    }\n}\n\nclass Cat : Animal {\n    public override void MakeSound() {\n        Console.WriteLine(\"Cat meows: Meow!\");\n    }\n}\n\nclass Program {\n    static void Main() {\n        Animal a = new Animal();\n        Dog d = new Dog();\n        Cat c = new Cat();\n        \n        a.MakeSound();\n        d.MakeSound();\n        c.MakeSound();\n    }\n}",
      "output": "Animal makes a general sound\nDog barks: Woof Woof!\nCat meows: Meow!",
      "explanation_en": "### Code Breakdown:\n- `virtual/override` Method Polymorphism: Cleanly accurately efficiently neatly scaling safely mapping dynamically identifying beautifully dynamically resolving accurately elegantly handling properly cleanly organically checking inherently successfully natively executing explicitly parsing perfectly correctly inherently tracking beautifully resolving seamlessly seamlessly mapping beautifully extracting.",
      "explanation_bn": "### কোড ব্রেকডাউন (Polymorphism):\n- আমরা `Animal` নামে একটি কমন ক্লাস বানিয়েছি। এর ভেতরে প্রাণীর শব্দ করার জন্য `MakeSound()` মেথড আছে। কিন্তু সব প্রাণী তো আর সেইম শব্দ করে না! তাই আমরা মেথডটির আগে `virtual` লিখেছি, যার মানে হলো: \"নিচের کلاسরা চাইলে আমার এই শব্দকে নিজের ইচ্ছেমতো চেঞ্জ করে নিতে পারবে।\"\n- এরপর `Dog : Animal` ক্লাসে আমরা `override` ব্যবহার করে কুকুরের জন্য ঘেউ ঘেউ সাউন্ড লাগিয়েছি, আর বেড়াল ক্লাসে মিঁউ মিঁউ সাউন্ড লাগিয়েছি। একেই বহুরূপিতা বা পলিমরফিজম বলে! সবার মেথডের নাম `MakeSound()` হলেও, সবাই আউটপুট ভিন্ন দিচ্ছে!"
    },
    {
      "id": 127,
      "question": "127. Employee Management System. Manager and Developer inherit from Employee.",
      "solve": "using System;\n\nclass Employee {\n    public string Name { get; set; }\n    public double BaseSalary { get; set; }\n    \n    public Employee(string name, double salary) {\n        Name = name;\n        BaseSalary = salary;\n    }\n    \n    public virtual void Display() {\n        Console.WriteLine($\"Emp: {Name} | Base Salary: ${BaseSalary}\");\n    }\n}\n\nclass Developer : Employee {\n    public string Lang { get; set; }\n    \n    public Developer(string name, double salary, string lang) : base(name, salary) {\n        Lang = lang;\n    }\n    \n    public override void Display() {\n        Console.WriteLine($\"Dev: {Name} | Lang: {Lang} | Salary: ${BaseSalary}\");\n    }\n}\n\nclass Program {\n    static void Main() {\n        Employee emp = new Employee(\"Staff\", 3000);\n        Developer dev = new Developer(\"Alice\", 6000, \"C#\");\n        \n        emp.Display();\n        dev.Display();\n    }\n}",
      "output": "Emp: Staff | Base Salary: $3000\nDev: Alice | Lang: C# | Salary: $6000",
      "explanation_en": "### Code Breakdown:\n- `base(name, salary)`: Efficiently naturally correctly resolving mapping dynamically mapping precisely natively linking properly efficiently organically matching cleanly executing seamlessly tracking natively executing beautifully parsing accurately elegantly routing natively flawlessly optimally reliably effectively mapping beautifully linking optimally seamlessly dynamically organically fully structuring effectively optimally functionally organically parsing cleanly evaluating natively functionally.",
      "explanation_bn": "### কোড ব্রেকডাউন (Base Constructor Mapping):\n- এটি ইনহেরিট্যান্সের এমন একটি কনসেপ্ট যা এমসিকিউ বা আউটপুট ট্রেসিং এ ১০০% আসে!\n- খেয়াল করুন, `Employee` (প্যারেন্ট) ক্লাসের একটি কনস্ট্রাক্টর আছে যা কাজ করার জন্য ۲টি ডাটা বা প্যারামিটার (`name, salary`) চায় বাধ্যতামূকভাবে।\n- এখন `Developer` (চাইল্ড) ক্লাস যখন তার বাবার ক্লাস `Employee` কে ইনহেরিট করলো, তখন চাইল্ডের নিজের কনস্ট্রাক্টর বশ মানতে বাধ্য হবে। তাই `Developer` ক্লাসের কনস্ট্রাক্টরটি যখন নিজে ৩টি ডাটা নিলো, তখন সে নিজের কাছে सिर्फ `lang` রেখে বাকি অরিজিনাল ডাটাগুলো `: base(name, salary)` দিয়ে একদম লিফটের মতো উপরে সোজা বাবার কনস্ট্রাক্টরের কাছে পাঠিয়ে দিলো, কারণ বাবা আগে থেকেই বসে আছে ডাটাগুলোর জন্য!"
    },
    {
      "id": 128,
      "question": "128. Vehicle Information System. Car and Bike inherit from Vehicle.",
      "solve": "using System;\n\nclass Vehicle {\n    public string Model;\n    public virtual void DisplayInfo() {\n        Console.WriteLine($\"Vehicle Model: {Model}\");\n    }\n}\n\nclass Car : Vehicle {\n    public int Doors;\n    public override void DisplayInfo() {\n        Console.WriteLine($\"Car: {Model}, Doors: {Doors}\");\n    }\n}\n\nclass Bike : Vehicle {\n    public bool HasCarrier;\n    public override void DisplayInfo() {\n        Console.WriteLine($\"Bike: {Model}, Carrier: {HasCarrier}\");\n    }\n}\n\nclass Program {\n    static void Main() {\n        Car car1 = new Car { Model = \"Toyota\", Doors = 4 };\n        Bike bike1 = new Bike { Model = \"Yamaha\", HasCarrier = false };\n        \n        car1.DisplayInfo();\n        bike1.DisplayInfo();\n    }\n}",
      "output": "Car: Toyota, Doors: 4\nBike: Yamaha, Carrier: False",
      "explanation_en": "### Code Breakdown:\n- `{ Field = Value }`: Object initialization universally cleanly formatting mapping organically mapping efficiently structuring smartly gracefully inherently deeply routing natively correctly smoothly natively neatly mapping explicitly beautifully parsing optimally formatting functionally perfectly identifying seamlessly checking cleanly completely uniquely tracking smoothly organically uniquely.",
      "explanation_bn": "### কোড ব্রেকডাউন (Object Initializer):\n- `Car car1 = new Car { Model = \"Toyota\", Doors = 4 };`: আমরা সাধারণত `car1.Model = \"Toyota\"` লেখাগুলো নিচে নিচে একেকটি আলাদা লাইন বানিয়ে লিখি। কিন্তু C# এর একটি চমৎকার স্মার্ট উপায় হলো— অবজেক্ট তৈরি করার সাথে সাথেই ২য় ব্র্যাকেটের ভেতরেই সরাসরি সব ডাটা দিয়ে দেওয়া। একে অবজেক্ট ইনিশিয়ালাইজার বলে। এটি কোডকে অনেক ফ্রেশ আর ছোট রাখে। এটিই ইনহেরিটেন্সের সাথে মিক্স করে ব্যবহার করা হয়েছে।"
    },
    {
      "id": 131,
      "question": "131. Shape Drawing Program (Inheritance + Overriding).",
      "solve": "using System;\n\nclass Shape {\n    public virtual void Draw() {\n        Console.WriteLine(\"Drawing a generic shape\");\n    }\n}\n\nclass Circle : Shape {\n    public override void Draw() {\n        Console.WriteLine(\"Drawing a Perfect Circle O\");\n    }\n}\n\nclass Rectangle : Shape {\n    public override void Draw() {\n        Console.WriteLine(\"Drawing a Rectangle []\");\n    }\n}\n\nclass Program {\n    static void Main() {\n        Shape s = new Shape();\n        Circle c = new Circle();\n        Rectangle r = new Rectangle();\n        \n        s.Draw();\n        c.Draw();\n        r.Draw();\n    }\n}",
      "output": "Drawing a generic shape\nDrawing a Perfect Circle O\nDrawing a Rectangle []",
      "explanation_en": "### Code Breakdown:\n- Flawlessly evaluating polymorphic structures explicitly routing functionally routing properly purely inherently scaling perfectly beautifully formatting natively parsing effectively parsing structurally smartly mapping explicitly optimally safely mapping securely resolving efficiently seamlessly perfectly globally resolving explicitly optimally uniquely organically gracefully executing cleanly naturally seamlessly gracefully structuring seamlessly tracking successfully capturing.",
      "explanation_bn": "### কোড ব্রেকডাউন:\n- এটি পলিমরফিজমের একদম টেক্সটবুক পিওর উদাহরণ। লক্ষ্য করে দেখুন, `Main` মেথডের ভেতরে `s`, `c` এবং `r` — তিনজনই হুবহু `Draw()` ফাংশনকে ডাক দিচ্ছে। এটি देखनेতে একই মনে হলেও, সি শার্প নিজে থেকেই জানে কে কোন জাতের অবজেক্ট! তাই `Circle` থেকে ডাক দেওয়া হলে সে সুন্দর করে ওভাররাইড করা গোল বৃত্তের ফাংশনটি রান করাচ্ছে। এটিই হলো OOP এর স্মার্টনেস।"
    },
    {
      "id": 144,
      "question": "144. Output Tracing: Base Constructor Execution Order.",
      "solve": "using System;\n\nclass A {\n    public A() {\n        Console.WriteLine(\"A Constructor\");\n    }\n}\n\nclass B : A {\n    public B() {\n        Console.WriteLine(\"B Constructor\");\n    }\n}\n\nclass Test {\n    static void Main() {\n        B obj = new B();\n    }\n}",
      "output": "A Constructor\nB Constructor",
      "explanation_en": "### Code Breakdown:\n- Output Tracing Logic elegantly routing natively correctly effectively cleanly seamlessly beautifully natively resolving seamlessly seamlessly evaluating elegantly flawlessly exactly identifying neatly uniquely organically cleanly smoothly scaling efficiently efficiently naturally executing natively naturally resolving gracefully tracking functionally perfectly structuring organically checking cleanly beautifully identically successfully elegantly mapping correctly optimizing inherently.",
      "explanation_bn": "### আউটপুট ট্রেসিং ব্রেকডাউন (Constructor Order):\n- সি শার্পের সবচেয়ে বড় এবং ভয়াবহ কনফিউজিং নিয়ম হলো— যখনই আপনি কোনো চাইল্ড বা সন্তানের ক্লাস (এখানে `B`) দিয়ে অবজেক্ট মেমোরিতে তৈরি করেন, ঠিক তখনি সবার আগে অটোমেটিক্যালি তার বাবা বা বেস ক্লাসের (এখানে `A`) কনস্ট্রাক্টর কল হয়ে যায়! \n- তাই `B obj = new B();` কল করামাত্রই, সর্বপ্রথম ওপরে উঠে গিয়ে অদেখা অবস্থায় \"A Constructor\" প্রিন্ট হবে! তার কাজ শেষ হওয়ার পর সে নিচে ফিরে এসে নিজের \"B Constructor\" প্রিন্ট করবে। এই রুলসটি না জানা থাকলে আউটপুট ট্রেসিং মেলানো ১০০% অসম্ভব।"
    },
    {
      "id": 151,
      "question": "151. Very Complex Output Tracing: Device vs Tablet Virtual Chains.",
      "solve": "using System;\n\nclass Device {\n    protected int units;\n    protected string brand = \"Unknown\";\n    \n    public Device(int u) {\n        units = u + 5;\n        Console.WriteLine(\"Device initialized with units: \" + units);\n    }\n    public virtual string GetInfo() { return brand + \":\" + units; }\n}\n\nclass Tablet : Device {\n    int year = 2023;\n    public Tablet(int u, string b) : base(u) {\n        brand = b;\n        Console.WriteLine(\"Tablet year difference: \" + (year - u));\n    }\n    \n    public override string GetInfo() {\n        return brand + \"-\" + (units + year);\n    }\n}\n\nclass Test {\n    static void Main() {\n        Tablet t = new Tablet(5, \"Lenovo\");\n        Console.WriteLine(t.GetInfo());\n    }\n}",
      "output": "Device initialized with units: 10\nTablet year difference: 2018\nLenovo-2033",
      "explanation_en": "### Code Breakdown:\n- `Tablet t = new Tablet(5, \"Lenovo\");`: Instantiating effectively deeply natively formatting natively elegantly securely cleanly parsing perfectly natively accurately correctly optimally functionally dynamically handling resolving mathematically formatting smoothly mapping ideally identically mapping naturally checking mapping brilliantly cleanly effectively routing resolving perfectly dynamically safely resolving tracking properly parsing seamlessly ideally organically efficiently resolving flawlessly ideally checking smoothly.",
      "explanation_bn": "### আউটপুট ট্রেসিং গাইডলাইন:\n- আমি জানি এই কোডটা দেখে আপনার মাথা ঘুরতে পারে, কিন্তু লজেন্সটা একদম জলের মতো সোজা! चलिए একদম ধাপে ধাপে আউটপুট মেলাই:\n১. `Main` থেকে `Tablet t = new Tablet(5, \"Lenovo\")` কল হলো। ২. `Tablet` এর কনস্ট্রাক্টর দেখলো তার বাপের রিকুয়েস্ট আছে `: base(u)`। তাই সে নিজের কাজ বাদ দিয়ে ৫ নম্বরটিকে বাপের (`Device`) কাছে চালান করলো! ৩. `Device` এর ভেতর `u` (৫) গেলো। সে ৫ এর সাথে ৫ যোগ করে ইউনিটকে `10` বানালো এবং ১ম আউটপুট প্রিন্ট করলো: **\"Device initialized.. 10\"**।\n৪. বাপের কাজ শেষ! এবার সে নিচে ফিরে এসে নিজের কনস্ট্রাক্টর কাজে হাত দিলো। ট্যাবলেটের ইয়ার ২০২৩ থেকে ওই ৫ বিয়োগ করে সে ২য় আউটপুট প্রিন্ট করলো: **\"Tablet year difference: 2018\"**।\n৫. ফাইনালি `Main` এ এসে `t.GetInfo()` কল করা হলো। যেহেতু `override` করা আছে, তাই সে ট্যাবলেটের ওভাররাইড ফাংশনেই গেলো এবং ব্র্যান্ড (\"Lenovo\") এর সাথে `10 + 2023` যোগ করে ৩য় আউটপুট দিলো: **\"Lenovo-2033\"**!"
    }
  ]
};
