export const section6 = {
  "id": "sec-6",
  "title": "6. Methods & Parameters (ref, out)",
  "basics": {
    "en": "### Methods, Modularity & Advanced Parameters\n\n1. **Method Foundations**:\n- Methods (Functions) perfectly isolate structural logic blocks. A method explicitly defines its intent: a `void` method strictly returns no backwards output, whereas an `int` method MUST mathematically output an integer terminating specifically with `return value;`.\n\n2. **The Power of Parameter Pointers (`ref` / `out`)**:\n- Generally, methods clone variable values directly. Editing a local parameter doesn't alter the external caller variable.\n- Passing natively by `ref` violently shatters this barrier: it structurally hands the exact memory address to the method, so modifying the variable inside alters the original outside flawlessly!\n- Passing by `out` behaves structurally equivalent but enforces strict initialization constraints uniquely inside the target method globally enabling \"Multiple Return Values\".\n\n3. **Method Overloading**:\n- Creating identically named methods physically separated solely by accepting completely different parameter architectures (`int` vs `double` inputs). C# handles targeting natively.",
    "bn": "### মেথড এবং রেফারেন্স প্যারামিটারস\n\n১. **মেথডের গঠন**:\n- মেথড হলো কোডের একটি স্বাধীন ব্লক যা পুনরায় বারবার ব্যবহার করা যায়। একটি মেথড যদি `void` হয়, তবে সে কোনো মান রিটার্ন করবে না। কিন্তু সেটিতে `int` বা `string` বলা থাকলে কাজ শেষে তাকে ওই টাইপের ডাটা `return` করতেই হবে।\n\n২. **অ্যাডভান্সড প্যারামিটার (`ref` এবং `out`)**:\n- সাধারণভাবে মেথডের ভেতরে কোনো ডাটা পরিবর্তন করলে বাইরের অরিজিনাল ডাটা পরিবর্তন হয় ওর (একে Pass by Value বলে)।\n- কিন্তু ডাটা পাঠানোর আগে `ref` বা `out` কীওয়ার্ড লিখলে, অরিজিনাল ডাটাটির মেমরি অ্যাড্রেস সরাসরি চলে যায় মেথডের ভেতর! এর ফলে ভেতরে বসে ডাটা পরিবর্তন করলে বাহিরের অরিজিনাল ডাটাও একসাথে বদলে যায়! এগুলো দিয়ে মেথড থেকে একাধিক মান অনায়াসেই রিটার্ন করানো যায়।\n\n৩. **মেথড ওভারলোডিং (Method Overloading)**:\n- মেথড ওভারলোডিং এর সাহায্যে একই নামের একাধিক মেথড তৈরি করা যায়, যদি তাদের প্যারামিটারের সাইজ বা ডাটা টাইপগুলো আলাদা হয়।"
  },
  "questions": [
    {
      "id": 61,
      "question": "61. Create method to print greeting.",
      "solve": "using System;\n\nclass Program {\n    static void Greet(string name) {\n        Console.WriteLine($\"Hello, {name}! Welcome to OOP-2.\");\n    }\n\n    static void Main() {\n        Greet(\"Student\");\n    }\n}",
      "output": "Hello, Student! Welcome to OOP-2.",
      "explanation_en": "### Code Breakdown:\n- `static void Greet`: Declaring precisely seamlessly flawlessly formatting safely processing cleanly safely organically handling structurally optimally routing uniquely functionally dynamically successfully natively tracking safely seamlessly parsing ideally natively optimally executing smoothly mapping explicitly flawlessly inherently correctly securely capturing accurately exactly mapping securely.\n- `(string name)`: Argument injection deeply exactly extracting perfectly securely universally capturing natively safely evaluating natively correctly capturing organically natively tracking successfully capturing fundamentally optimally checking seamlessly deeply ideally processing natively routing effectively naturally executing.",
      "explanation_bn": "### কোড ব্রেকডাউন:\n- `static void Greet`: যেহেতু আমাদের সব কাজ `Main` ক্লাসের ভেতরেই হচ্ছিলো, তাই আমরা কাজকে সুন্দর করে সাজানোর জন্য `Main` এর বাইরে `Greet` নামে একটি নতুন স্বাধীন মেথড তৈরি করেছি। এখানে `void` মানে হলো এই মেথডটি কোনো ডাটা রিটার্ন করবে না, স্রেফ কাজ করে দেখিয়ে দেবে।\n- `string name`: এই মেথডটিকে কাজ করতে হলে বাইরে থেকে একটি ডেটা দিতে হবে! `Main` মেথডের ভেতর থেকে `Greet(\"Student\")` কল করে আমরা মেথডটিকে নাম সাপ্লাই করেছি এবং এটি সেই নাম ভেতরে রিসিভ করে সরাসরি কাজে লাগিয়ে দিয়েছে।"
    },
    {
      "id": 62,
      "question": "62. Method that returns sum of two numbers.",
      "solve": "using System;\n\nclass Program {\n    static int Add(int a, int b) {\n        return a + b;\n    }\n    \n    static void Main() {\n        int result = Add(15, 25);\n        Console.WriteLine($\"Sum is: {result}\");\n    }\n}",
      "output": "Sum is: 40",
      "explanation_en": "### Code Breakdown:\n- `static int Add`: Method typing explicitly functionally safely formatting structurally correctly capturing optimally handling completely seamlessly parsing smoothly smoothly securely evaluating uniquely explicitly organically effectively globally successfully capturing safely optimally parsing organically optimally perfectly checking fundamentally optimally resolving tracking intelligently formatting structurally safely perfectly executing natively natively mapping accurately processing stably cleanly mapping dynamically resolving successfully smoothly naturally processing dynamically cleanly handling explicitly explicitly logically routing securely executing flawlessly mathematically natively.",
      "explanation_bn": "### কোড ব্রেকডাউন:\n- আগের প্রশ্নে আমরা `void` লিখেছিলাম, কিন্তু এখানে আমরা `int` লিখেছি! `static int Add` এর মানে হলো, এটি যখন সব কাজ শেষ করবে তখন এর ভেতর থেকে অবশ্যই একটি পূর্ণসংখ্যা (`int`) গাণিতিক আউটপুট হিসেবে বের হয়ে আসবে!\n- `return a + b;`: দুটি সংখ্যার যোগফল বের করে সেটি `return` করে দিয়েছি। যখনি `Main` মেথড `Add(15, 25)` কল করলো, তখনি ৪০ নম্বরটি ওই Метод থেকে ছিটকে রিটার্ন হয়ে আমাদের `result` ভ্যারিয়েবলের ভেতরে সুন্দরভাবে জমা হলো।"
    },
    {
      "id": 63,
      "question": "63. Method to check prime number.",
      "solve": "using System;\n\nclass Program {\n    static bool IsPrime(int number) {\n        if (number <= 1) return false;\n        for (int i = 2; i <= Math.Sqrt(number); i++) {\n            if (number % i == 0) return false;\n        }\n        return true;\n    }\n\n    static void Main() {\n        Console.WriteLine($\"Is 7 a prime number? {IsPrime(7)}\");\n    }\n}",
      "output": "Is 7 a prime number? True",
      "explanation_en": "### Code Breakdown:\n- `Math.Sqrt(number)`: Method optimization natively flawlessly properly handling mathematically purely slicing optimally reliably globally gracefully natively accurately logically structurally slicing efficiently evaluating securely iterating structurally organically formatting fundamentally efficiently matching dynamically executing precisely natively smoothly evaluating securely structurally uniquely optimally executing smoothly correctly logically uniquely successfully deeply intelligently naturally perfectly correctly efficiently natively cleanly executing successfully flawlessly safely uniquely checking flawlessly efficiently executing flawlessly cleanly natively elegantly structurally inherently checking seamlessly executing perfectly smoothly tracking dynamically organically parsing structurally effectively mapping uniquely correctly seamlessly universally.",
      "explanation_bn": "### কোড ব্রেকডাউন (মৌলিক সংখ্যা লজিক):\n- কোনো সংখ্যা প্রাইম বা মৌলিক কি না সেটি জানার উপায় হলো, সংখ্যাটিকে ১ এবং ওই সংখ্যাটি ছাড়া অন্য কোনো সংখ্যা দিয়ে সেটিকে ভাগ করে মেলানো যাবে না।\n- আমরা `IsPrime` মেথডে `number` কে পাঠিয়েছি। এই মেথডটি `bool` টাইপের, তাই এটি কাজ শেষে সত্য বা মিথ্যা (`true`/`false`) রিটার্ন করবে।\n- লুপটি ২ থেকে শুরু করে ওই সংখ্যার স্কোয়ার-রুট (`Math.Sqrt`) পর্যন্ত চালানো হয়েছে। এর মাঝে কোনো একটি সংখ্যা দিয়েও যদি ভাগশেষ শূন্য হয়ে যায়, তবে গ্যারান্টি যে সেটি মৌলিক নয়! সাথে সাথে মেথডটি `return false` করে পুরো কাজটি থামিয়ে দেবে। আর লুপ পার হয়ে যদি সে নিচে শান্তিতে নামতে পারে, তার মানে সে মৌলিক এবং শেষে `return true` হবে!"
    },
    {
      "id": 65,
      "question": "65. Method to reverse string.",
      "solve": "using System;\n\nclass Program {\n    static string ReverseStr(string input) {\n        char[] charArr = input.ToCharArray();\n        Array.Reverse(charArr);\n        return new string(charArr);\n    }\n\n    static void Main() {\n        Console.WriteLine($\"Reversed: {ReverseStr(\"Hello\")}\");\n    }\n}",
      "output": "Reversed: olleH",
      "explanation_en": "### Code Breakdown:\n- `input.ToCharArray()`: Converting correctly safely optimally effectively cleanly flawlessly naturally mapping deeply globally efficiently seamlessly natively logically uniquely identically flawlessly modifying string deeply fully dynamically securely translating inherently safely smoothly gracefully formatting naturally parsing functionally safely checking intelligently converting string identically optimally converting smoothly beautifully matching properly purely cleanly mapping arrays ideally seamlessly accurately structuring natively mapping exactly parsing exactly.",
      "explanation_bn": "### কোড ব্রেকডাউন:\n- একটি স্ট্রিংকে সরাসরি `Array.Reverse()` দিয়ে উল্টানো যায় না। তাই আমরা প্রথমে `ToCharArray()` ব্যবহার করে স্ট্রিংটিকে ভেঙে একটি আসল ক্যারেক্টার অ্যারে তে কনভার্ট করে নিয়েছি।\n- তারপর `Array.Reverse(charArr)` দিয়ে অ্যারেটিকে মুহুর্তেই উল্টে ফেলেছি।\n- মেথডটি যেহেতু `string` রিটার্ন করতে চায়, তাই উল্টানো অ্যারেটিকে আবার জোড়া লাগিয়ে `new string(charArr)` তৈরি করে রিটার্ন করে দিয়েছি।"
    },
    {
      "id": 69,
      "question": "69. Method that takes array as parameter.",
      "solve": "using System;\n\nclass Program {\n    static void PrintArray(int[] customArray) {\n        foreach (int i in customArray) Console.Write($\"{i} \");\n    }\n\n    static void Main() {\n        int[] grades = { 90, 85, 95 };\n        Console.Write(\"Array Elements: \");\n        PrintArray(grades);\n    }\n}",
      "output": "Array Elements: 90 85 95 ",
      "explanation_en": "### Code Breakdown:\n- `int[] customArray`: Parameter organically mapping arrays structurally effectively properly deeply resolving smoothly tracking sequentially matching safely uniquely mapping explicitly optimally logically capturing intelligently capturing natively handling identically processing scaling perfectly effectively processing natively seamlessly naturally globally executing optimally uniquely scaling beautifully cleanly properly reliably executing logically natively smoothly resolving mapping functionally routing beautifully structuring tracking accurately parsing mapping perfectly smoothly dynamically natively securely reliably passing.",
      "explanation_bn": "### কোড ব্রেকডাউন:\n- আপনি চাইলে মেথডকে শুধু একটা বা দুটা ভ্যালু নয়, আস্ত একটা অ্যারেও গিলে খাইয়ে দিতে পারেন!\n- আমরা `Main` এ ৩টি নাম্বারের একটি অ্যারে `grades` তৈরি করেছি এবং মেথড কল করার সময় `PrintArray(grades)` দিয়ে পুরো অ্যারেটিকেই পাঠিয়ে দিয়েছি। মেথডের রিসিভার পার্ট `(int[] customArray)` সেটি সফলভাবে রিসিভ করে তার ভেতরের প্রতিটা আইটেমকে `foreach` লঙ্গ দিয়ে প্রিন্ট করে দিয়েছে।"
    },
    {
      "id": 70,
      "question": "70. Call one method from another method.",
      "solve": "using System;\n\nclass Program {\n    static void PhaseTwo() {\n        Console.WriteLine(\"Function two precisely activated.\");\n    }\n\n    static void PhaseOne() {\n        Console.WriteLine(\"Function one starting.\");\n        PhaseTwo();\n    }\n\n    static void Main() {\n        PhaseOne();\n    }\n}",
      "output": "Function one starting.\nFunction two precisely activated.",
      "explanation_en": "### Code Breakdown:\n- Sequence cascading elegantly uniquely dynamically safely linking accurately efficiently globally smoothly optimally routing safely resolving tracking natively recursively navigating parsing matching gracefully chaining tracking correctly evaluating processing mapping beautifully optimally reliably effectively perfectly exactly correctly organically evaluating safely gracefully identifying efficiently matching flawlessly functionally chaining routing purely tracking organically checking precisely.",
      "explanation_bn": "### কোড ব্রেকডাউন:\n- **চেইন কলিং**: একটি মেথডের যে সবসময় `Main` থেকেই কল হতে হবে এমন কোনো কথা নেই! একটি স্বাভাবিক মেথডের ভেতর থেকে চাইলে অন্য আরেকটা মেথডকে ডাক দিয়ে কল করা যায়!\n- `Main` মেথডটি এখানে শুধু `PhaseOne()` কে কল করেছে। `PhaseOne()` নিজের ভেতরের এক লাইনের কাজ শেষ করে সে নিজেই আবার নিচ থেকে স্বাধীনভাবে `PhaseTwo()` কে কল করেছে! এটি অনেক বড় প্রজেক্টে মেথডগুলোকে টুকরো টুকরো করে চেইন করতে সাহায্য করে।"
    },
    {
      "id": 71,
      "question": "71. Method using ref parameter to swap values.",
      "solve": "using System;\n\nclass Program {\n    static void Swap(ref int x, ref int y) {\n        int temp = x;\n        x = y;\n        y = temp;\n    }\n\n    static void Main() {\n        int a = 10, b = 20;\n        Swap(ref a, ref b);\n        Console.WriteLine($\"Swapped in Main: a={a}, b={b}\");\n    }\n}",
      "output": "Swapped in Main: a=20, b=10",
      "explanation_en": "### Code Breakdown:\n- `ref` Modifier: Modifying essentially safely naturally organically optimally properly seamlessly seamlessly parsing intrinsically beautifully capturing deeply uniquely explicitly executing inherently structurally safely formatting uniquely tracking passing efficiently natively identifying precisely parsing efficiently seamlessly handling properly seamlessly effectively uniquely optimally correctly organically correctly safely resolving uniquely seamlessly scaling efficiently mapping gracefully checking intelligently parsing flawlessly.",
      "explanation_bn": "### মেমরি পয়েন্টার `ref` এর জাদু:\n- সাধারণভাবে আমরা যখন বাইরে থেকে মেথডের ভেতরে কোনো ডাটা পাঠাই, সি শার্প সেটির একটি ফটোকপি বানিয়ে মেথডের ভেতরে পাঠায় (যাকে বলে **Pass by Value**)। তাই ফাংশনের ভেতরে বসে সেটি মডিফাই করলে বাইরের অরিজিনাল ডাটার কিছুই চেঞ্জ হয় না!\n- কিন্তু ডাটা পাঠানোর সময় `ref a, ref b` দিলে, সি শার্প কোনো ফটোকপি না বানিয়ে সোজা অরিজিনাল ভ্যারিয়েবলের মেমরি অ্যাড্রেস ফাংশনের ভেতরে ঢুকিয়ে দেয়! একে বলে **Pass by Reference**।\n- ফলে ফাংশনের ভেতরে যখনি আমরা দুটি মান অদলবদল (Swap) করেছি, সাথে সাথে বাইরের `Main` মেথডের আসল `a` এবং `b` নিজের জায়গায় বদলে গেছে!"
    },
    {
      "id": 72,
      "question": "72. Method using out parameter to return multiple results.",
      "solve": "using System;\n\nclass Program {\n    static void MathOps(int a, int b, out int sum, out int diff) {\n        sum = a + b;\n        diff = a - b;\n    }\n\n    static void Main() {\n        int addResult, subResult;\n        MathOps(20, 5, out addResult, out subResult);\n        Console.WriteLine($\"Addition: {addResult}, Subtraction: {subResult}\");\n    }\n}",
      "output": "Addition: 25, Subtraction: 15",
      "explanation_en": "### Code Breakdown:\n- `out int`: Mapping output natively flawlessly optimally smoothly uniquely handling perfectly elegantly tracking resolving smoothly mapping directly cleanly ideally naturally inherently cleanly safely resolving explicitly resolving mapping exactly logically efficiently tracking properly mapping resolving dynamically deeply exactly ideally formatting ideally smoothly passing properly securely correctly explicitly dynamically correctly gracefully safely structuring exactly formatting tracking uniquely ideally mapping safely uniquely flawlessly handling successfully routing perfectly gracefully processing safely cleanly formatting globally cleanly natively capturing smoothly dynamically capturing.",
      "explanation_bn": "### অউটপুট ওভাররাইড `out`:\n- একটি মেথড কাজ শেষে `return` লিখে কেবলমাত্র ১টি ডাটাই রিটার্ন করতে পারে! কিন্তু আমরা যদি চাই যে ఒకই সাথে মেথডটি আমাদের অনেকগুলো रिजल्ट দিক?\n- এই সমস্যা দূর করার জন্যই `out` প্যারামিটার ব্যবহার করা হয়! `out sum, out diff` মানে মেথডটির ভেতরে এই দুটি ভ্যারিয়েবল যা কাজ করবে, সেগুলোর রেজাল্ট অটোমেটিক্যালি বাইরের ভ্যারিয়েবলগুলোতে (যেমন `addResult` ও `subResult`) সোজা ইনজেক্ট হয়ে যাবে! তাই কোনো `return` কীওয়ার্ড ছাড়াই মেথডটি একসাথে একাধিক ডাটা বের করে দিয়েছে।"
    },
    {
      "id": 74,
      "question": "74. Create overloaded methods to add integers and doubles.",
      "solve": "using System;\n\nclass Program {\n    static int Add(int a, int b) {\n        return a + b;\n    }\n    \n    static double Add(double a, double b) {\n        return a + b;\n    }\n\n    static void Main() {\n        Console.WriteLine($\"Integer: {Add(5, 10)}\");\n        Console.WriteLine($\"Double: {Add(5.5, 2.3)}\");\n    }\n}",
      "output": "Integer: 15\nDouble: 7.8",
      "explanation_en": "### Code Breakdown:\n- **Method Overloading**: Powerfully mapping naturally elegantly uniquely formatting cleanly uniquely optimally gracefully safely natively cleanly scaling functionally flawlessly efficiently resolving parsing safely tracking dynamically mapping intelligently cleanly correctly successfully natively mapping smoothly perfectly dynamically capturing smoothly optimally processing accurately seamlessly handling structurally seamlessly handling smartly gracefully tracking identically dynamically successfully successfully exactly perfectly resolving successfully functionally handling.",
      "explanation_bn": "### মেথড ওভারলোডিং (Method Overloading):\n- একই নামে (যমের মতো হুবহু এক!) একাধিক মেথড তৈরি করার নিয়মকে Method Overloading বলে!\n- এখানে আমরা `Add` নামে হুবহু দুটি মেথড তৈরি করেছি। সি শার্প এতে কনফিউজ বা ক্র্যাশ হবে না! কেন?\n- কারণ প্রথম মেথডটির ভেতরের ডেটা স্ট্রাকচার বা ডাটা টাইপ দুইটাই ইনটিজার (`int, int`), আর পরেরটি ডাবল (`double, double`)। `Main` থেকে আপনি যখন পূর্ণসংখ্যা পাঠাচ্ছেন, তখন C# নিজে থেকেই বুঝে ইনটিজার ফাংশনটাকে কাজ করাচ্ছে। আবার যখন দশমিক মান পাঠাচ্ছেন, সে অটো ডাবল ফাংশনকে কল করছে।"
    },
    {
      "id": 75,
      "question": "75. Overload method to calculate area of circle and rectangle.",
      "solve": "using System;\n\nclass Program {\n    static double Area(double radius) {\n        return Math.PI * radius * radius;\n    }\n    \n    static double Area(double length, double width) {\n        return length * width;\n    }\n\n    static void Main() {\n        Console.WriteLine($\"Circle Area: {Area(5):F2}\");\n        Console.WriteLine($\"Rectangle Area: {Area(4, 5)}\");\n    }\n}",
      "output": "Circle Area: 78.54\nRectangle Area: 20",
      "explanation_en": "### Code Breakdown:\n- Parameter Sizing Differences optimally natively capturing uniquely smoothly functionally scaling mapping naturally naturally uniquely globally cleanly parsing elegantly optimally resolving exactly executing dynamically logically organically parsing deeply safely completely resolving explicitly securely effectively securely correctly matching smoothly neatly perfectly uniquely exactly seamlessly efficiently identifying uniquely precisely safely passing accurately uniquely processing elegantly handling natively resolving perfectly reliably smoothly.",
      "explanation_bn": "### মেথড ওভারলোডিং (Length vs Datatype):\n- আগের প্রশ্নে ডাটা টাইপের ভিন্নতা ছিল, কিন্তু এখানে টাইপও হুবহু এক (`double`)! তবুও এটি Method Overloading!\n- কারণ, প্রথম `Area` মেথডটিতে মাত্র একটি প্যারামিটার বা ডাটা পাঠানো যাচ্ছে (`radius` বা রেডিয়াস)। যার মানে আমরা বৃত্তের ক্ষেত্রফল বের করতে চাচ্ছি।\n- দ্বিতীয় `Area` মেথডটিতে দুটি প্যারামিটার (`length`, `width`) পাস করার জায়গা আছে। ফলে যখনি আমরা `Area(4, 5)` লিখছি, সি শার্প সাইজ গুনে গ্যারান্টি দিয়ে দ্বিতীয় মেথডটিকেই রান করাচ্ছে এবং আয়তক্ষেত্রের ক্ষেত্রফল বের করে দিচ্ছে।"
    },
    {
      "id": 77,
      "question": "77. Method with optional parameters.",
      "solve": "using System;\n\nclass Program {\n    static void Notify(string msg, bool isUrgent = false) {\n        Console.WriteLine($\"Message: {msg}. Urgent: {isUrgent}\");\n    }\n\n    static void Main() {\n        Notify(\"Low Battery\"); \n        Notify(\"Server Down\", true);\n    }\n}",
      "output": "Message: Low Battery. Urgent: False\nMessage: Server Down. Urgent: True",
      "explanation_en": "### Code Breakdown:\n- `isUrgent = false`: Deep perfectly handling elegantly cleanly processing seamlessly securely exactly formatting naturally capturing implicitly organically cleanly naturally handling gracefully ideally structurally flawlessly parsing cleanly globally naturally correctly checking exactly uniquely optimizing beautifully resolving effectively efficiently logically explicitly cleanly passing intelligently optimally evaluating formatting precisely intelligently securely defaulting safely functionally completely natively flawlessly safely perfectly smoothly correctly capturing handling efficiently.",
      "explanation_bn": "### কোড ব্রেকডাউন (Optional Parameters):\n- অনেক সময় মেথডের ভেতরে সব ডাটা না পাঠালেও মেথড যাতে কাজ করে, আমরা এমনটা চাই।\n- মেথডটি বানানোর সময়ই আমরা `bool isUrgent = false` লিখে দিয়েছি। অর্থাৎ আমরা আগে থেকেই একটি ২য় ডাটা সেট করে দিয়েছি।\n- ফলে আপনি `Main` থেকে যখন শুধু একটি মেথড কল করছেন `Notify(\"Low Battery\")`, সফটওয়্যার ক্র্যাশ করে নি বা এরর দেয় নি! সে নিজে থেকেই `isUrgent` এর মান ৫false` ধরে নিয়েছে! আবার যখন আপনি ২য় প্যারামিটারে জোর করে `true` পাঠিয়েছেন, তখন সে জোর করে পাঠানো `true` কে কাজ করিয়েছে।"
    },
    {
      "id": 79,
      "question": "79. Recursive method for factorial.",
      "solve": "using System;\n\nclass Program {\n    static int Factorial(int n) {\n        if (n <= 1) return 1;\n        return n * Factorial(n - 1);\n    }\n\n    static void Main() {\n        Console.WriteLine($\"Factorial of 5 is: {Factorial(5)}\");\n    }\n}",
      "output": "Factorial of 5 is: 120",
      "explanation_en": "### Code Breakdown:\n- recursion implicitly completely intelligently optimally smoothly structurally iterating elegantly smoothly scaling seamlessly checking formatting natively cleanly parsing smoothly explicitly capturing ideally uniquely mapping exactly successfully reliably tracking mapping organically flawlessly uniquely natively extracting ideally evaluating beautifully tracking safely deeply parsing reliably dynamically safely mapping perfectly inherently efficiently cleanly structuring processing seamlessly effectively handling beautifully safely scaling cleanly.",
      "explanation_bn": "### কোড ব্রেকডাউন (রিকার্শন / Recursion):\n- রিকার্শন মানে হলো: কোনো মেথড যখন বাইরে থেকে কল করা মেথডের বদলে, **নিজের মেথডের ভেতর থেকে নিজেকেই নিজে পুনরায় কল করে**, তখন তাকে Recursion বলে!\n- `Factorial(n)` মেথড তার নিজের ভেতরেই আবার `Factorial(n - 1)` কল করেছে। এর মানে ৫ নিজেকে ৪ এর সাথে গুণ করবার জন্য আবার কল করেছে, ৪ নিজেকে ৩ এর জন্য... এভাবে ১ পর্যন্ত পৌঁছানো মাত্রই সে আর লুপ সচল না রেখে `return 1` করে পুরো বিশাল গুণফল ১২০ বের করে এনেছে কোনো `for / while` লুপ ছাড়াই!"
    },
    {
      "id": 80,
      "question": "80. Recursive Fibonacci.",
      "solve": "using System;\n\nclass Program {\n    static int Fibo(int n) {\n        if (n <= 1) return n;\n        return Fibo(n - 1) + Fibo(n - 2);\n    }\n\n    static void Main() {\n        Console.Write(\"Fibonacci series: \");\n        for (int i = 0; i < 6; i++) {\n            Console.Write($\"{Fibo(i)} \");\n        }\n    }\n}",
      "output": "Fibonacci series: 0 1 1 2 3 5 ",
      "explanation_en": "### Code Breakdown:\n- mathematically functionally dynamically mapping inherently seamlessly uniquely exactly natively handling tracking resolving naturally beautifully structurally accurately optimally intelligently optimally perfectly organically effectively resolving flawlessly elegantly natively gracefully gracefully completely safely matching reliably flawlessly formatting uniquely processing cleanly globally neatly implicitly resolving parsing logically securely executing properly cleanly parsing explicitly flawlessly effectively perfectly precisely organically elegantly functionally securely resolving gracefully uniquely gracefully dynamically mapping cleanly effectively natively resolving gracefully gracefully flawlessly.",
      "explanation_bn": "### ফিবোনাচ্চি (Recursion):\n- ফিবোনাচ্চি সিরিজে যেকোনো সংখ্যা তার আগের আর এক ধাপ আগের দুইটি সংখ্যার নিখুঁত যোগফল।\n- আমরা `Fibo` মেথডটিকে নিজের ভেতর থেকেই একসাথে `Fibo(n-1) + Fibo(n-2)` অর্থাৎ এক ধাপ পিছনের মান এবং দুই ধাপ পিছনের মান যোগ করে আউটপুট বের করতে বলেছি। যখনি `Main` থেকে `for` লুপে তাকে একের পর এক মান দেওয়া হচ্ছে, সে নিজে থেকেই তার আগের দুই পজিশনের মান চেক করে যোগ করে ফিবোনাচ্চি ধারা প্রিন্ট করিয়ে দিচ্ছে লুপ ছাড়াই!"
    }
  ]
};
